apiVersion: v1
kind: Service
metadata:
  name: myweb-service-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: web-app-test
    region: IN
    env: testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-dep-test
  labels:
    app: web-app-test
    framework: react
    region: IN
spec:
  replicas: 3
  selector:
    matchExpressions:
      - { key: env, operator: In, values: [testing]}
      - { key: region, operator: In, values: [IN]}
      - { key: app, operator: In, values: [web-app-test]}
  template:
    metadata:
      name: myweb-pod-test
      labels:
        env: testing
        region: IN
        app: web-app-test
    spec:
      containers:
        - name: myweb-con
          image: smc181002/react-hello
          ports:
            - containerPort: 80
              name: react-app
          volumeMounts:
            - name: react-pvc
              mountPath: /usr/local/apache2/htdocs
      volumes:
         - name: react-pvc
           persistentVolumeClaim:
              claimName: pv-claim-name
