apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: web-app
    region: IN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-dep
  labels:
    app: web-app
    framework: react
    region: IN
spec:
  replicas: 3
  selector:
    matchExpressions:
      - { key: env, operator: In, values: [production]}
      - { key: region, operator: In, values: [IN]}
  template:
    metadata:
      labels:
        env: production
        region: IN
        app: web-app

      name: myweb-pod
    spec:
      containers:
        - name: myweb-con
          image: smc181002/react-hello
          ports:
            - containerPort: 80
              name: react-app
          volumeMounts:
            - name: react-pvc
              mountPath: /usr/local/apache2/htdocs
      volumes:
         - name: react-pvc
           persistentVolumeClaim:
              claimName: pv-claim-name
