apiVersion: v1
kind: Service
metadata:
  name: html-hello
  labels:
    app: html-hello
spec:
  selector:
    env: production
    app: htmlhello
  type: NodePort
  # ClusterIP and LoadBalancer are other options
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-hello
spec:
  selector:
    matchExpressions:
    - {key: env, operator: In, values: [production]}
    - {key: app, operator: In, values: [htmlhello]}
  template:
    metadata:
      name: html-pod
      labels:
        env: production
        app: htmlhello
    spec:
      containers:
      - name: html-hello
        image: smc181002/html-hello:1
