apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - nodePort: 32123
      port: 8080
  selector:
    app: jenkins
    tier: task3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
    tier: task3
spec:
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [jenkins]}
    - {key: tier, operator: In, values: [task3]}
  template:
    metadata:
      labels:
        app: jenkins
        tier: task3
    spec:
      containers:
      - image: smc181002/jenk_kubectl
        name: jenkins-app
        ports:
        - containerPort: 8080
          name: jenkins
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /root/.jenkins/
        - name: server-pv-claim-files
          mountPath: /home/
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: server-pv-claim-files
        persistentVolumeClaim:
           claimName: pv-claim-name 
