apiVersion: v1
kind: Pod
metadata:
  name: myweb-pod2
  labels:
    country: IND
    name: myweb
    dc: "2"
    env: testing

spec:
  containers:
  - name: second-one
    image: httpd
    volumeMounts:
      - name: pvc-volume
        mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: pv-claim-name
